### ISSUE TITLE
Error while running tests on ubuntu 

### ISSUE THREAD

**Issue by atyamsriharsha** [datascienceinc/Skater#265]
======================================================================
ERROR: skater.tests.test_data (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: skater.tests.test_data
Traceback (most recent call last):
  File "/home/sriharsha/miniconda/envs/skater-test/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/sriharsha/miniconda/envs/skater-test/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sriharsha/Skater/skater/tests/test_data.py", line 8, in <module>
    from arg_parser import arg_parse, create_parser
ModuleNotFoundError: No module named 'arg_parser'

======================================================================
ERROR: skater.tests.test_partial_dependence (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: skater.tests.test_partial_dependence
Traceback (most recent call last):
  File "/home/sriharsha/miniconda/envs/skater-test/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/sriharsha/miniconda/envs/skater-test/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/sriharsha/Skater/skater/tests/test_partial_dependence.py", line 13, in <module>
    from arg_parser import create_parser
ModuleNotFoundError: No module named 'arg_parser'

**Comment by darenr** [comment]
Can you please provide more details, version of Ubuntu, version of python for example.

**Comment by atyamsriharsha** [comment]
Python 3.6.7 :: Anaconda, Inc.
Ubuntu 18.04.1 LTS 
can you also provide me instructions to install arg_parser module ?

**Comment by darenr** [comment]
there is no install for the arg_parser module, it's part of the Skater source code. Take a look in skater/tests/arg_parser.py

This makes me wonder how you installed Skater, are you installing the source from github and running the tests with:
```python skater/tests/all_tests.py```
I just tried it on Same Ubuntu with 3.6.7 from the source tree and had no problems. Maybe this is a packaging issue if you're running the tests from the pip installed package?
